// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimG9fTopwZVnSodYn0hIOAT-86E3YBY0',
    appId: '1:672967801268:web:13e9c40352e0ec2da65ae1',
    messagingSenderId: '672967801268',
    projectId: 'carpoolbudy',
    authDomain: 'carpoolbudy.firebaseapp.com',
    storageBucket: 'carpoolbudy.appspot.com',
    measurementId: 'G-D17NTQEKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYyHwWwhftGpPjCylZXO51f1_FDOebePU',
    appId: '1:672967801268:android:9ad2798ca10372b7a65ae1',
    messagingSenderId: '672967801268',
    projectId: 'carpoolbudy',
    storageBucket: 'carpoolbudy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6Ei_Q4nlICc5FKwjR1XKKrZlpEyatKQ',
    appId: '1:672967801268:ios:38a2a17e0bd7db92a65ae1',
    messagingSenderId: '672967801268',
    projectId: 'carpoolbudy',
    storageBucket: 'carpoolbudy.appspot.com',
    androidClientId: '672967801268-31cjrv8ldafd09k2esjh3q35t4iqub1u.apps.googleusercontent.com',
    iosClientId: '672967801268-ef2vvqdvo8rfre0n9go7h6deurc1tlqh.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
